Repository mus-ali1/sharing-is-caring, pull requests merged in 2021-09, with the labels that each got.

#2 Setup
  .gitignore
  package-lock.json
  package.json
  public/css/style.css
  public/js/login.js
  server.js
Labels: good first issue

#6 Ticket 3mvc folders
  controllers/api/index.js
  controllers/index.js
  model/Comment.js
  model/Recipes.js
  model/User.js
  model/index.js
  views/login.handlebars
Labels: enhancement

#7 Add: config folder & connection.js
  config/connection.js
Labels: enhancement

#10 Ticket 8 create db structure
  db/schema.sql
  seeds/index.js
Labels: enhancement

#11 install dependencies
  package-lock.json
  package.json
Labels: enhancement

#20 Added sequelize, db connection, express session
  server.js
Labels: enhancement

#22 Add: declared handlebars & app.engine + app.set
  server.js
Labels: enhancement

#23 complete connection.js
  config/connection.js
Labels: enhancement

#26 Ticket15 create user db
  model/User.js
Labels: enhancement

#27 .DS_Store added to .gitignore
  .gitignore
Labels: bug

#28 Ticket 24 create recipes db
  model/Recipes.js
Labels: enhancement

#29 Ticket 25 create comments db
  model/Comment.js
Labels: enhancement

#32 Ticket 30 update index js model
  model/index.js
Labels: enhancement

#33 Ticket31 change recipes reference
  model/Comment.js
  model/Recipe.js
  model/index.js
Labels: enhancement

#40 Ticket36 index.js file completed in seeds folder
  controllers/index.js
  seeds/index.js
Labels: enhancement

#41 Added recipe json file to seed folder
  seeds/recipe.json
Labels: enhancement

#42 Cr user.json & added seed data
  seeds/user.json
Labels: enhancement

#43 Ticket39 add json file for comment
  controllers/index.js
  seeds/comment.json
  seeds/index.js
Labels: enhancement

#44 bug fixes
  model/Comment.js
  model/Recipe.js
  model/index.js
  seeds/comment.json
  seeds/index.js
  seeds/recipe.json
Labels: bug

#46 Ticket 45 add text column to comment db
  .env.EXAMPLE
  model/Comment.js
  package.json
  seeds/comment.json
Labels: enhancement

#50 Ticket 16 create routes and files for controllers
  controllers/api/CommentRoutes.js
  controllers/api/RecipeRoutes.js
  controllers/api/UserRoutes.js
  controllers/api/index.js
  server.js
Labels: enhancement

#51 Ticket 47 create user route
  controllers/api/UserRoutes.js
  controllers/api/index.js
  package-lock.json
  package.json
  server.js
Labels: enhancement

#52 Ticket 48 create recipe routes
  controllers/api/RecipeRoutes.js
  controllers/api/index.js
  utils/auth.js
Labels: enhancement

#53 Ticket49 create comment route
  controllers/api/CommentRoutes.js
  controllers/api/index.js
Labels: enhancement

#55 Ticket54 create home routes
  controllers/homeRoutes.js
Labels: enhancement

#57 Ticket 56 complete controller index js
  controllers/index.js
Labels: enhancement

#59 Ticket 58 create main handlebars
  public/js/logout.js
  views/layouts/main.handlebars
Labels: enhancement

#61 Ticket60 add login handlebars
  views/login.handlebars
Labels: enhancement

#68 Ticket 5 complete readme.md
  README.md
  package.json
Labels: documentation

#73 Ticket 62 complete login js in public folder
  public/js/login.js
  views/login.handlebars
  views/signUp.handlebars
Labels: enhancement

#75 ADD: logout functionality in public folder
  public/js/logout.js
  views/layouts/main.handlebars
Labels: enhancement

#77 Bug fixes and comment js file
  model/Recipe.js
  public/js/comment.js
  public/js/login.js
  views/homepage.handlebars
  views/layouts/main.handlebars
  views/signUp.handlebars
  views/single-recipe.handlebars
Labels: enhancement

#81 Ticket79 styling for login and signup pages + bug fixes
  controllers/api/UserRoutes.js
  controllers/homeRoutes.js
  images/backgroundForLogin.jpg
  public/js/create-recipe.js
  public/js/login.js
  views/create-recipe.handlebars
  views/dashboard.handlebars
  views/homepage.handlebars
  views/layouts/main.handlebars
  views/login.handlebars
  views/single-recipe.handlebars
Labels: enhancement

#83 Ticket82 bug fixes and style pages
  controllers/api/RecipeRoutes.js
  controllers/api/UserRoutes.js
  controllers/homeRoutes.js
  images/backgroundForLogin.jpg
  model/Recipe.js
  public/css/style.css
  public/images/backgroundForLogin.jpg
  public/js/create-recipe.js
  public/js/login.js
  public/js/signup.js
  views/create-recipe.handlebars
  views/dashboard.handlebars
  views/layouts/main.handlebars
  views/login.handlebars
  views/partials/create-recipe.handlebars
  views/signUp.handlebars
Labels: bug

#85 fixed typo
  controllers/homeRoutes.js
Labels: bug

#87 Ticket 86 complete readme
  README.md
  public/images/ScreenshotSharingCaring.png
Labels: enhancement
